# Making a Basic Neural Network From First Principals
## Adam Fletcher

The idea is that I will construct a very simple neural network from first principals with the goal of gaining an understanding of how a basic neural network functions.

This will provide a great amount of insight into troubleshooting neural network problems as well as giving me insight into the limitations of these networks.

In [1]:
import numpy as np

## Define the class NeuralNetwork

In [2]:
# Activation function
def sigmoid(t):
    return 1/(1+np.exp(-t))

# Derivative of sigmoid
def sigmoid_derivative(p):
    return p * (1 - p)

In [3]:
# Class definition
class NeuralNetwork:
    def __init__(self, x,y):
        np.random.seed(1)
        self.input         = x
        self.weights1      = np.random.rand(self.input.shape[1],4)
        self.weights2      = np.random.rand(4,1)
        self.y             = y
        self.output        = np.zeros(y.shape)
        self.learning_rate = 1
        self.bias1         = 0 #currently set to zero, add way to alter bias
        self.bias2         = 0 #currently set to zero, add way to alter bias
        
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1)  + self.bias1 ) #make bias do stuff
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2) + self.bias2 ) #make bias do stuff
        return self.layer2
    
    def loss_function(self):
        self.loss = (np.mean(np.square(self.y - self.feedforward())))
        return self.loss
        
    def backprop(self):
        # calculates the derivative 
        d_weights2 = np.dot(
            self.layer1.T, 
            2*(self.y - self.output) * sigmoid_derivative(self.output)
            #2*(y-y^) is the partial derivative of the sum of squares error
        )    
        
        d_weights1 = np.dot(
            self.input.T, 
            np.dot(
                2*(self.y - self.output) * sigmoid_derivative(self.output), 
                self.weights2.T)
            * sigmoid_derivative(self.layer1)
        )
        
        ##d_bias2 = np.dot()
            
        
    
        
        self.weights1   += (d_weights1 * self.learning_rate)
        self.weights2   += (d_weights2 * self.learning_rate)
        #self.bias1      += (d_weights1 * self.learning_rate)
        #self.bias2      += (d_weights2 * self.learning_rate)

    def train(self, X, y):
        self.output = self.feedforward()
        self.backprop()
    

### Todo
- calculate cost function
- make sure backpropagation is working correctly
- add a learning rate
- add a bias

In [4]:
# Each row is a training example, each column is a feature  [X1, X2, X3]
X=np.array(([0,0,1],[0,1,1],[1,0,1],[1,1,1]), dtype=float)
y=np.array(([0],[1],[1],[0]), dtype=float)
NN = NeuralNetwork(X,y)

In [5]:
NN.feedforward()

array([[0.75751918],
       [0.77108221],
       [0.79094709],
       [0.80118439]])

In [6]:

for i in range(1501): # trains the NN 1,000 times
    if i % 100 ==0: 
        print ("for iteration # " + str(i) + "\n")
        print ("Input : \n" + str(X))
        print ("Actual Output: \n" + str(y))
        print ("Predicted Output: \n" + str(NN.feedforward()))
        print ("Loss: \n" + str(NN.loss_function())) # mean sum squared loss
        print ("\n")
  
    NN.train(X, y)

for iteration # 0

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.75751918]
 [0.77108221]
 [0.79094709]
 [0.80118439]]
Loss: 
0.32795955373606145


for iteration # 100

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.47735688]
 [0.50734278]
 [0.51014619]
 [0.52233385]]
Loss: 
0.24584253174174747


for iteration # 200

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.20756081]
 [0.64505943]
 [0.6381092 ]
 [0.50302353]]
Loss: 
0.13826547915301574


for iteration # 300

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.06940067]
 [0.84714493]
 [0.84654485]
 [0.18783807]]
Loss: 
0.02175318668762149


for iteration # 400

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 